format = '$all$directory$character'

right_format = "$azure$cmd_duration$time$battery$kubernetes"

[azure]
disabled = false
format = '[$symbol($subscription)]($style) '
symbol = 'ó° … '
style = 'blue bold'
align = 'right'

[kubernetes]
format = '[âŽˆ ($context)]($style) '
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "ðŸ’” " },
]

[line_break]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
